fix(tomcat config): execute the validation query before returning a connection from the pool (#89)
Adding testOnBorrow="true" to cope with CommunicationsException: The last packet successfully received from the server was 45 869 049 milliseconds ago.
SocketException: Software caused connection abort: socket write error